# -*- coding: utf-8 -*-
"""legalrepQA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDwqH2YLqon2MG9nfhA0NCRgQU0_CZ4j
"""

!pip install transformers langchain sentence-transformers

from huggingface_hub import login


login(token="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")

from transformers import pipeline
qa_pipeline = pipeline("question-answering", model="deepset/roberta-base-squad2")

context = """
The lease agreement is between the landlord and the tenant. The tenant agrees to pay a rent of $1000 monthly due on the 1st of each month.
In case of non-payment for 3 consecutive months, the landlord has the right to begin eviction proceedings.
The tenant is responsible for maintaining the property and paying for any damages caused.
"""
question = "What happens if the tenant doesn't pay rent for 3 months?"

answer = qa_pipeline(question=question, context=context)

print(answer['answer'])

questions = [
    "What is the rent amount?",
    "Who is responsible for property maintenance?",
    "What happens if the tenant damages the property?",
    "Can the landlord evict the tenant for subletting the property?"
]

for question in questions:
    answer = qa_pipeline(question=question, context=context)
    print(f"Question: {question}")
    print(f"Answer: {answer['answer']}\n")

!pip install flask

from flask import Flask, jsonify
from threading import Thread

app = Flask(__name__)

# Add a new route
@app.route('/new-route', methods=['GET'])
def new_route():
    return jsonify({"message": "This is a new route from Colab!"})

# Function to run the app
def run():
    app.run(host='0.0.0.0', port=5000)

# Run the app in a separate thread
thread = Thread(target=run)
thread.start()

from pyngrok import ngrok

# Replace 'your_auth_token' with the token you copied from the Ngrok dashboard
ngrok.set_auth_token('2uPEV4uiMIRvtw5MVHxBOSgMI0U_2pSWfnguRNez3H97JH3Ta')

# Now, you can start the Flask app and expose it via Ngrok
public_url = ngrok.connect(5000)
print("Flask app is running at:", public_url)